config/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include("home.urls")),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path('home/' , views.user_list , name = 'home'),
    path('search/' , views.search_user , name = 'serachuser'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    first_name = models.CharField(null=True, blank=True, verbose_name='First name', max_length=100, unique=True)
    last_name = models.CharField(null=True, blank=True, verbose_name='Last name', max_length=100, unique=True)
    username = models.CharField(null=True, blank=True, max_length=100)
    email = models.EmailField(null=True, blank=True)
    phone_number1 = models.CharField(max_length=20, null=False, blank=False, unique=True, verbose_name='Phone Number')
    phone_number2 = models.CharField(max_length=20, null=True, blank=True, unique=True, verbose_name='Phone Number 2')
    side = models.CharField(max_length=100, verbose_name='Side',  blank=True)
    office = models.CharField(max_length=100, verbose_name='Office', blank=True)

    USERNAME_FIELD = 'phone_number1'
    REQUIRED_FIELDS = ['email', 'username']
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.phone_number1

home/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


# Show profile
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('username', 'email', 'password1', 'password2')


# Change profile
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

home/forms.py
from django import forms

class UserSearchForm(forms.Form):
    search = forms.CharField(max_length=100 , label="search" )

accounts/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render
from accounts.models import CustomUser
from .forms import UserSearchForm

def user_list(request):
    ls_user = CustomUser.objects.all()
    form = UserSearchForm()
    return render(request , 'home/main.html' , context={"ls_user":ls_user , "forms" : form} )

def search_user(request):
    search = request.GET.get("search")
    ls_user = CustomUser.objects.filter(username__icontains=search)

    if ls_user.exists() == True :
        return render(request, "home/main.html", {"ls_user": ls_user})
    else:
        ls_user = CustomUser.objects.filter(phone_number1__icontains=search)
        return render(request, "home/main.html", {"ls_user": ls_user})

home/templates/home/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>

<body>

<form action="{% url "home:serachuser" %}" method="get">

    {{ forms }}
</form>
    <div class="main">
        <table style="width: 90%; text-align: center; margin: 20px auto;">
            <tr>
                <th>S.NO.</th>
                <th>NAME</th>
                <th>ID</th>
                <th>PHONE</th>
                <th>WORKING STATUS</th>
                <th>DEPARTMENT</th>
                <th>ADDRESS</th>
            </tr>
            {% for user in ls_user %}
                <tr>
                <td>1</td>
                <td>{{ user.username }}</td>
                <td>{{ user.id }}</td>
                <td>{{ user.phone_number1 }}</td>
                <td>true</td>
                <td>{{ user.office }}</td>
                <td>tehran</td>
            </tr>
            {% endfor %}

        </table>
        
    </div>
</body>
</html>